In [7]:
import datetime
import numpy as np
import pandas as pd
import warnings
from scipy.stats import pearsonr
warnings.filterwarnings('ignore')

In [8]:
def day_price_ret(ticker_symbol,s_date,e_date):
    stock_symbol = ticker_symbol

    stock_data = yf.download(stock_symbol, start=s_date, end=e_date)
    stock_data = stock_data.set_index(pd.to_datetime(stock_data.index))

    weekly_returns = stock_data['Adj Close'].pct_change().dropna()

    return pd.DataFrame(weekly_returns)

In [9]:
stock_all = pd.read_csv('전체기간.csv',index_col = 0)

In [10]:
stock_all

,코스피,코스닥,SK㈜,롯데쇼핑,HD현대,서부티앤디,하나금융지주,SK리츠,롯데리츠,코람코라이프인프라리츠,신한서부티앤디리츠,코람코더원리츠
Date,,,,,,,,,,,,
2022-04-04,0.006588,0.007176,0.024845,0.014359,0.012963,0.004854,0.002066,0.006211,-0.005172,0.007764,0.009690,0.024263
2022-04-05,0.000471,0.005436,0.000000,-0.002022,0.009141,0.028986,-0.028866,-0.001543,-0.010399,0.009245,-0.003839,0.037225
2022-04-06,-0.008760,-0.009806,0.004040,-0.010132,-0.005435,-0.023474,0.007431,-0.010819,-0.012259,0.009160,0.015414,0.019576
2022-04-07,-0.014322,-0.016095,-0.010060,-0.021494,-0.007286,0.000000,-0.015806,0.006250,0.003546,0.019667,-0.001898,-0.011200
2022-04-08,0.001680,0.007306,0.008130,-0.011506,0.005505,0.004808,-0.007495,0.010870,0.014134,0.008902,0.020913,0.001618
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-25,-0.003998,0.010741,-0.017259,-0.017520,-0.011611,0.004087,-0.021875,0.016970,0.000000,0.001965,0.000000,0.001988
2024-03-26,0.007130,0.002627,0.002661,0.012346,0.008811,-0.010855,-0.019169,-0.005959,0.000000,0.000000,-0.002407,0.000000
2024-03-27,-0.000718,-0.005283,-0.016985,-0.004065,0.007278,0.008230,-0.040717,-0.005995,-0.010606,-0.011765,-0.009650,-0.007937
2024-03-28,-0.003372,-0.001317,-0.014039,0.001361,-0.004335,0.004082,0.000000,-0.013269,-0.006126,0.003968,0.002436,-0.003000
2024-03-29,0.000295,-0.005000,-0.002792,-0.019022,0.043541,0.009485,-0.020374,0.002445,-0.004622,0.001976,0.002430,0.000000

In [11]:
d_ret_df = stock_all.describe()

In [12]:
d_ret_df.loc[['mean','std','min','50%','max'],['코스피','코스닥','SK㈜','SK리츠','롯데쇼핑','롯데리츠','HD현대','코람코라이프인프라리츠','서부티앤디','신한서부티앤디리츠','하나금융지주','코람코더원리츠']]

,코스피,코스닥,SK㈜,SK리츠,롯데쇼핑,롯데리츠,HD현대,코람코라이프인프라리츠,서부티앤디,신한서부티앤디리츠,하나금융지주,코람코더원리츠
mean,0.000058,0.000037,-0.000340,-0.000486,-0.000283,-0.000868,0.001030,-0.000278,-0.000189,-0.000025,0.000869,5.385993e-07
std,0.010566,0.015172,0.019410,0.014820,0.018535,0.012091,0.017074,0.010715,0.021549,0.014022,0.020078,1.207911e-02
min,-0.035194,-0.050716,-0.067647,-0.063253,-0.076582,-0.058386,-0.056569,-0.049419,-0.077095,-0.061497,-0.059423,-5.645181e-02
50%,0.000250,0.000507,-0.000860,0.000000,-0.001232,0.000000,0.000000,0.000000,-0.001350,0.000000,0.000000,0.000000e+00
max,0.056592,0.073397,0.099251,0.079872,0.086183,0.049383,0.064371,0.036972,0.121554,0.071082,0.087866,5.721395e-02

In [13]:
d_ret_df.to_csv('대주주_기초통계량.csv')